### ISSUE TITLE
[Feature request] Some Features/Suggestions To Improve The Functionality Of Youtubuddy

### ISSUE THREAD

**Issue by Spectrum75** [Botspot/youtubuddy#1]
### I like youtubuddy very much and below are some features/suggestions that I think will greatly improve the functionality of it. 

**1. **Thumbnail Size Option [SOLVED]****
An option for the thumbnail size will be great, especially for people running the pi with mini TFT touchscreen displays. Will also improve the GUI.

**2. **Video Playback Quality Option [SOLVED]**** 
This is a must have option for YouTube apps. Adding an option for changing the quality will be of great help for people with older pi models or people with slow internet connection who would like to watch the videos at a lower resolution.

**3. **Launching VLC Media Player In Full Screen [SOLVED]****
Since youtubuddy uses VLC Media Player to play videos, it will be nice to launch it in full screen mode itself. The show controls in full screen mode option is enabled by default on the pi.

**4. [REMOVED]**

**5. **Video Won't Be Selected If It Is Not Tick Marked [SOLVED]****
This happens that even if you have selected a video to play (the column turns blue) and click the `play`button, it won't play, you have to go and put the tick mark to the video for it to play. I feel this a bit annoying and a fix would be great.

**6. **Youtubuddy Won't Relaunch Itself, Once VLC Media Player Is Closed [SOLVED]****
If vlc media player is closed for (example I don't like the video) then Youtubuddy won't relaunch itself again, you have to go to the menu and launch it manually. It would be nice to see it launching itself automatically just like pi-apps does after running the install or uninstall script for an app. I think it would be better to add this like an option so users can change it according to their needs.

**7. Video Download Quality Option [SOLVED]**
Just like there should be an option for video playback quality, it would also be great to have a video download quality option. 
I think it downloads the videos in the highest quality possible by default because the size for a 10 minute video is like 450 mb,
which is obviously a high resolution video like 720p or 1080p.

These are the changes that I think adding in the stable release will greatly help improve youtubuddy. Keep going @Botspot 😊

**Comment by Botspot** [comment]
About number 5, I'm not sure how to improve.

It's nice to play/download multiple videos at once, right? The downside is that you have to click the checkbox. I also found out that double-clicking will also toggle the checkbox.

**Comment by Spectrum75** [comment]
Oh, I just forgot about that but it will be still nice to have it like an option for users who need it 😀

**Comment by Botspot** [comment]
@spectrumgamer75 I think I've added everything you asked for with commit 82b13fa9152d12fdc49cc91bb23455b365740bd0.

**Comment by Spectrum75** [comment]
@Botspot The thumbnail size is perfect, what about the video quality? also what are these `args` for vlc and youtube-dl? 
What can they be used for?

**Comment by Botspot** [comment]
> @Botspot The thumbnail size is perfect, what about the video quality? also what are these `args` for vlc and youtube-dl?
> What can they be used for?

The args give you as much flexibility as desired. For example, to make VLC run in fullscreen, add the `-f` flag. See all vlc flags by running `vlc --help`.  
Same thing with youtube-dl - there's got to be some sort of video quality flag to set.

Let me know how it goes.

**Comment by Spectrum75** [comment]
Thanks for that option @Botspot will let you know once I get the correct flags for them :+1:

**Comment by spectrumgamer75** [comment]
For setting the video quality I found the following steps to be working:
**Open VLC:**
- Go to tools>preferences

- Enable "All" option in settings 

- In the left pane select "input/codecs" then on the right pane in "track settings" click preferred resolution option and select the video quality.

**Comment by Spectrum75** [comment]
When I tried setting the download quality by following this:
https://askubuntu.com/questions/486297/how-to-select-video-quality-from-youtube-dl#486298

I get the the error "`ERROR: youtube-dl is not a valid URL`". Isn't the download option using youtube-dl? or does the download quality code changes with the videos?

**Comment by Botspot** [comment]
> I get the the error "`ERROR: youtube-dl is not a valid URL`". Isn't the download option using youtube-dl?

Are you trying to put `youtube-dl` in the `Youtube-dl args` field? No, just put ***flags***, like `-c` (I made that `-c` up)

**Comment by Spectrum75** [comment]
So, no need to add `youtube-dl` again right? Now got it :)

**Comment by Spectrum75** [comment]
@Botspot Is it also possible to bring a kind of homepage like you have when you open youtube?

**Comment by Botspot** [comment]
> So, no need to add youtube-dl again right? Now got it :)

Correct.

> @Botspot Is it also possible to bring a kind of homepage like you have when you open youtube?

What would be **on** this "homepage" you speak of?  
Recommended videos? Not possible. It's surprisingly hard to determine what videos, out of millions, are the most relevant for you, especially for a bash-based program that does not have AI, or access to your browsing history.

**Comment by Spectrum75** [comment]
> > So, no need to add youtube-dl again right? Now got it :)
> 
> Correct.
> 
> > @Botspot Is it also possible to bring a kind of homepage like you have when you open youtube?
> 
> What would be **on** this "homepage" you speak of?
> Recommended videos? Not possible. It's surprisingly hard to determine what videos, out of millions, are the most relevant for you, especially for a bash-based program that does not have AI, or access to your browsing history.

oh, ok :)

**Comment by spectrumgamer75** [comment]
For changing **download quality** as I had mentioned earlier, follow:
https://askubuntu.com/questions/486297/how-to-select-video-quality-from-youtube-dl#486298
