### ISSUE TITLE
watchlist only remembers one video

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/youtubuddy#12]
example: I search for one video, I add it to the watchlist. then I find another video that I want to watch later.
now if I open the watchlist I only see the last video I added to it.

**Comment by Botspot** [comment]
Thanks for the bug report. I've been able to reproduce it.

**Comment by Botspot** [comment]
Should be fixed now with commit 7637fec35cd678e6b8911c971e5b6418f13110d2.

Problem was solved by adding one character to the script! Amazing.

**Comment by Itai-Nelken** [comment]
amazing! anyway it fixed it.

**Comment by Botspot** [comment]
Awesome. Thank you.
