### ISSUE TITLE
Anyone having "infinite search" issues?

### ISSUE THREAD

**Issue by Botspot** [Botspot/youtubuddy#13]
I've noticed that for some searches, youtubuddy tries to load the results forever, but never succeeds.

Upon closer investigation, I believe I've found a bug in `youtube-dl`'s source code. I've opened [an issue](https://github.com/ytdl-org/youtube-dl/issues/27604) on the youtube-dl repository, but it was closed almost immediately because some guy "can't reproduce" it.

Can you guys try running this command and seeing if your youtube-dl has the same issue as mine does?
```
youtube-dl -sv --print-json ytsearch1:battlebots
# and
youtube-dl -sv --print-json ytsearch1:youtubuddy
# Both of the above commands should produce A TON of output. If they don't, then you've experienced the same bug I found!
```
If the same bug occurs for you, I encourage you to leave a comment on [the youtube-dl issue](https://github.com/ytdl-org/youtube-dl/issues/27604), saying that the bug affects you too.

**Comment by Itai-Nelken** [comment]
are both the commands supposed to be the same?
anyway they both create a lot of output.

**Comment by Botspot** [comment]
> are both the commands supposed to be the same?

No they are not. There, I've fixed it.

**Comment by Itai-Nelken** [comment]
the first command (`youtube-dl -sv --print-json ytsearch1:battlebots`) returns a ton of output, but the 2nd one doesn't.
here is the output of it (`youtube-dl -sv --print-json ytsearch1:youtubuddy`)
```sh
pi@Twisterpi4-ultra-4gb:~ $ youtube-dl -sv --print-json ytsearch1:youtubuddy
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-sv', u'--print-json', u'ytsearch1:youtubuddy']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.31
[debug] Python version 2.7.16 (CPython) - Linux-5.4.79-v7l+-armv7l-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 5, rtmpdump 2.4
[debug] Proxy map: {}
```

**Comment by Botspot** [comment]
The second one didn't return any output? That is good news! Please consider leaving a comment on the youtube-dl issue, saying that the bug affects you too.

**Comment by NoozAbooz** [comment]
@Botspot Hey, I've had a similar issue, but with a different bug in the youtubuddy code. When you add a youtube-dl flag, there needs to be a space in front or else it infinitely searches.

**Comment by Botspot** [comment]
> @Botspot Hey, I've had a similar issue, but with a different bug in the youtubuddy code. When you add a youtube-dl flag, there needs to be a space in front or else it infinitely searches.

What line in the code needs a space character?

**Comment by NoozAbooz** [comment]
I meant as in that when I add a flag, so for example `-f 135+140`, it searches infinitely. I believe that happens due to a bug where the code doesn't add a space when searching, and does something like `youtube-dl-f 135+140` instead of `youtube-dl -f 135+140`

**Comment by Itai-Nelken** [comment]
I always have a youtube-dl flag, and I never got a infinite serach. I also just tried `-f 135+140` and it still doesn't search ininitely.

**Comment by Itai-Nelken** [comment]
@Botspot why not make youtubuddy to download and compile youtube-dl until the updated version is added to `pip`

**Comment by Botspot** [comment]
> @Botspot why not make youtubuddy to download and compile youtube-dl until the updated version is added to `pip`

How long does it take to compile?

**Comment by Itai-Nelken** [comment]
> How long does it take to compile?

around 7 seconds (on a pi4 4gb stock clock speed using 4 threads) not including the git clone.
the git clone took me about 30 seconds with my super bad ~5mbits internet, so I would say it will take less than 30 seconds average.

**Comment by Itai-Nelken** [comment]
@Botspot the new version is available from `pip`.
https://pypi.org/project/youtube_dl/

**Comment by Botspot** [comment]
> @Botspot the new version is available from `pip`.
> https://pypi.org/project/youtube_dl/

Awesome! I've updated the `gui` script to upgrade youtube-dl. Would anyone like to try it?

**Comment by Itai-Nelken** [comment]
> Awesome! I've updated the `gui` script to upgrade youtube-dl. Would anyone like to try it?

I 'm pretty sure it upgraded youtube-dl fine and I have no more infinite search issue.
