### ISSUE TITLE
check for youtube-dl in other locations + suggestions

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/youtubuddy#14]
I just installed youtube-dl in a fresh Ubuntu 20.04 (x64) install, and youtubuddy had trouble installing pip, so it failed to install youtube-dl.
**my suggestion:** install youtube-dl from `apt` if pip fails.
now youtubuddy searched for youtube-dl in `/usr/local/bin` but youtube-dl from apt was in `/usr/bin`, so I made a link to it in `/usr/local/bin/` and that messed up youtube-dl. so I installed it from snap and changed the line in `gui` where it checks for youtube-dl to `snap/bin/youtube-dl`.
**my 2nd suggestion:** check for youtube-dl in `~/snap/bin/youtube-dl` and `/usr/bin/youtube-dl` as well as where it already checks (`/usr/local/bin/youtube-dl`).

**Comment by Itai-Nelken** [comment]
trouble installing pip because it has a different package name that I haven't found yet.

**Comment by Botspot** [comment]
The apt repo's version of youtube-dl is slower and out of date.

Remember the infinite search issue? That was recently fixed and available on `pip`. The APT version is ancient.

**Comment by Itai-Nelken** [comment]
then compile it from source, also its newer in the ubuntu repos and works well with youtubuddy (didn't check infinite search issue with it though).

**Comment by Botspot** [comment]
> trouble installing pip because it has a different package name that I haven't found yet.

Are these them? `python-pip` and `python3-pip`

**Comment by Itai-Nelken** [comment]
> Are these them? `python-pip` and `python3-pip`

no, `python-pip` doesn't exist.

**Comment by Botspot** [comment]
> > Are these them? `python-pip` and `python3-pip`
> 
> no, `python-pip` doesn't exist.

Weird. `apt search pip`

**Comment by Itai-Nelken** [comment]
> Weird. `apt search pip`

closest package is `python-pip-lhw` (or something similar, I don't remember).

**Comment by Botspot** [comment]
> The apt repo's version of youtube-dl is slower and out of date.
> 
> Remember the infinite search issue? That was recently fixed and available on `pip`. The APT version is ancient.
