### ISSUE TITLE
add option to use different media player

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/youtubuddy#2]
so far this app is great, but unfortunately the VLC version available from `apt` crashes my system, so I have the flatpak version that uses this command to start: ` flatpak run org.videolan.VLC `.
that means I can't play videos using this app wich is a shame. it will be great if a settings app (similar to pi-apps or PPT settings) in wich you can select a default media player (or insert the command to start your media player).
here is a example:
![youtubebuddy-settings-concept](https://user-images.githubusercontent.com/70802936/102088903-3393c880-3e24-11eb-906c-620e444bc419.png)

**Comment by Itai-Nelken** [comment]
I'm trying to add this feature in my fork here: https://github.com/Itai-Nelken/youtubuddy

**Comment by Botspot** [comment]
> that means I can't play videos using this app wich is a shame.

Youtubuddy is one bash script. You are welcome to edit the `gui` script and change the vlc command to whatever you want.

And yes, I was planning on adding this setting. Yes I will add it. But in the meantime, editing a bash script is really easy.

**Comment by Itai-Nelken** [comment]
of course I can edit it, thats what i did.
>I was planning on adding this setting

Great!

**Comment by Botspot** [comment]
Okay this has been added with commit 82b13fa9152d12fdc49cc91bb23455b365740bd0.
