### ISSUE TITLE
Videos not playing once opened via VLC

### ISSUE THREAD

**Issue by ghost** [Botspot/youtubuddy#20]
So basically, when using YoutuBuddy today, the videos just straight up wouldn't open, so I decided to launch via Command Line to see if there's any error messages there. There was.

Apparently everything seems to work just fine, until after VLC opens, in which case it states the following

``` bash
[9eb3b128] lua stream error: Couldn't extract youtube video URL, please check for updates to this script
```

This leads to VLC opening, but having no video at all, just a blank screen and if you interact with it; it'll ask you to open a video.

Not sure if this is an error brought on by myself, the Lua Script being broken or out of date, or something else entirely. Anyways have a good day.

**Comment by ghost** [comment]
It's a problem with VLC, so I'll just close the issue.

**Comment by Botspot** [comment]
Yeah I hope they update VLC soon. It has been this way for a while after Youtube made changes.
