### ISSUE TITLE
vlc commnad and youtube-dl arguments get mixed up

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/youtubuddy#3]
the vlc command appears in th youtube-dl args text box, and the youtube-dl args gets deleted. but the data is there because the app works as it should.

**Comment by Itai-Nelken** [comment]
they do get saved, but don't display correctly in the settings

**Comment by Itai-Nelken** [comment]
now they didn't get saved, the vlc command got into the `ytdl-args` file and the youtube-dl args got "lost"

**Comment by Itai-Nelken** [comment]
they do stay in place if I manually enter them into the files.

**Comment by Botspot** [comment]
Unfortunately I have not been able to repeat this bug.

**Comment by Spectrum75** [comment]
I have no such issue too, every thing works fine.

**Comment by Itai-Nelken** [comment]
[youtubuddy-bug.mp4.zip](https://github.com/Botspot/youtubuddy/files/5696454/youtubuddy-bug.mp4.zip)
here is a screen recording of what happens.
I found something else also, it only happens when you add a youtube-dl argument, watch the screen recording.

**Comment by Botspot** [comment]
Thanks. I think I figured it out.

Everything works fine, until one of the fields contains something starting with `--`. When that happens, yad assumes that's a yad-flag, and hides it. Then the remaining data fields are shifted up.

I'm not sure how to circumvent this yad bug.

**Comment by Botspot** [comment]
Okay I figured it out. By inserting any character in front of the `--`, yad ignores this "flag" and allows it do be displayed in the text box.

I could put a space character in front of it, OR, I found out you can use a **zero-width space** character. It's basically hidden and you won't even notice.

**Comment by Itai-Nelken** [comment]
>zero-width space character

is that this? `()`? I added it before adding the flag, and it works.

**Comment by Botspot** [comment]
> > zero-width space character
> 
> is that this? `()`? I added it before adding the flag, and it works.

No. With a [zero width space unicode character](https://codepen.io/chriscoyier/pen/iLKwm), you can't even see it in the text box.

**Comment by Botspot** [comment]
Okay it should be fixed now with commit 181a4742623372691f13e07828a5bc95d61aed4f.

Can anyone test that it indeed works?

**Comment by Itai-Nelken** [comment]
@Botspot it works now. 
Thanks for your great work!

**Comment by Botspot** [comment]
Awesome.
