### ISSUE TITLE
add download from link option

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/youtubuddy#4]
like SavUTube, add a textbox where you paste a link and can download/play it.

**Comment by Botspot** [comment]
I could probably add this functionality to the existing search box.

**Comment by Spectrum75** [comment]
It would be better to like add this as another functionality instead of adding it to the existing search box.

**Comment by Itai-Nelken** [comment]
> I could probably add this functionality to the existing search box.

actually that's a good idea, just replace `Search YouTube:` with `search youtube or paste link:`.

**Comment by Spectrum75** [comment]
> > I could probably add this functionality to the existing search box.
> 
> actually that's a good idea, just replace `Search YouTube:` with `search youtube or paste link:`.

But how will I know if it will play or download the video?

**Comment by Itai-Nelken** [comment]
> But how will I know if it will play or download the video?

I don't know, maybe if text entered starts with `https://` or `youtu.be`

**Comment by Itai-Nelken** [comment]
> But how will I know if it will play or download the video?

sorryI misread your question. I mean you paste a link, then the app checks if the video is available (if yes, download the thumbnail etc.) and than you can select if you want to play or download the video.
in other words just like searching, just you paste the link, so only 1 result.

**Comment by Spectrum75** [comment]
> > But how will I know if it will play or download the video?
> 
> sorryI misread your question. I mean you paste a link, then the app checks if the video is available (if yes, download the thumbnail etc.) and than you can select if you want to play or download the video.
> in other words just like searching, just you paste the link, so only 1 result.

yeah, a nice integration :)

**Comment by Botspot** [comment]
As of commit 9fe6a1571d8a68f7867649e408279064b02b308f, YouTubuddy now supports URLs and playlists.

Also I've worked on the images & branding a lot.
