### ISSUE TITLE
Search Box Accepts Complete Blank Inputs

### ISSUE THREAD

**Issue by Spectrum75** [Botspot/youtubuddy#7]
Hello,
I have found out a small bug in youtubuddy, that is that if you type just blank (space bar) without any thing then also it would go for searching videos and would say "something is wrong". I think this is a bit strange and should be fixed?

Thanks.

**Comment by Botspot** [comment]
Fixed with commit 51ba7a6e360888fb49a32db2d93480e6ee31cb63.

**Comment by Spectrum75** [comment]
Thanks :+1:
